### ISSUE TITLE
https://chicocode.io/pt-br/posts/revisitando-soma-dos-quadrados

### ISSUE THREAD

**Issue by chicocode** [chicocode/chicocodeio#6]
Como partir de uma abordagem imperativa de soma dos quadrados para uma abordagem funcional através passos. O intuito é aprender como pensar de modo funcional, e não apenas apresentar a solução funcional de um problema.

**Comment by WennderSantos** [comment]
Como já havia comentado, excelente post!
Acabei de fazer em haskell, [aqui](https://github.com/WennderSantos/haskell-study/blob/master/soma-quadrado.hs).

**Comment by chicocode** [comment]
Obrigado @WennderSantos ! Fico feliz que tenha gostado, e sua implementação também ficou muito massa!

**Comment by WennderSantos** [comment]
@chicocode _refactoring_ para usar _function composition_. Ainda não entendi muito bem o conceito matemático do recurso, mas, a primeira impressão foi de menor legibilidade. O que acha?

[commit 63bbe78d132493e485769b876a1c36249622f878](https://github.com/WennderSantos/haskell-study/commit/63bbe78d132493e485769b876a1c36249622f878#diff-c6ec7b24b15cdb83d844543fe6afb881)

**Comment by chicocode** [comment]
@WennderSantos Achei ótimo! Vejo a composição de funções como uma das principais ferramentas para reutilização de código em paradigmas funcionais. O recurso por si só é totalmente baseado na matemática. Isso significa que encontrar os quadrados de um array e depois somar é equivalente a somar os quadrados de um array diretamente. Parece não trazer ganhos quando só olhamos assim, mas tem padrões baseados em "hackear" as composições para criar comportamentos específicos, como é o caso do [ROP](https://fsharpforfunandprofit.com/rop/).
